apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zmzkmek9t-go 
  janus-idp.io/tekton: zmzkmek9t-go
  backstage.io/kubernetes-id: zmzkmek9t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zmzkmek9t-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml